// Countries the platform can onboard. A country needs (a) a currency the platform knows and
// (b) either a ready-made compliance pack or the generic template (rates entered by an admin).
module.exports = [
  { code: 'GH', name: 'Ghana', currency: 'GHS', locales: ['en'] },
  { code: 'LR', name: 'Liberia', currency: 'LRD', locales: ['en'] },
  { code: 'CI', name: "Côte d'Ivoire", currency: 'XOF', locales: ['fr'] },
  { code: 'NG', name: 'Nigeria', currency: 'NGN', locales: ['en'] },
  { code: 'KE', name: 'Kenya', currency: 'KES', locales: ['en', 'sw'] },
  { code: 'TZ', name: 'Tanzania', currency: 'TZS', locales: ['en', 'sw'] },
  { code: 'UG', name: 'Uganda', currency: 'UGX', locales: ['en'] },
  { code: 'RW', name: 'Rwanda', currency: 'RWF', locales: ['en', 'fr'] },
  { code: 'ZA', name: 'South Africa', currency: 'ZAR', locales: ['en'] },
  { code: 'ZM', name: 'Zambia', currency: 'ZMW', locales: ['en'] },
  { code: 'ZW', name: 'Zimbabwe', currency: 'ZWL', locales: ['en'] },
  { code: 'MW', name: 'Malawi', currency: 'MWK', locales: ['en'] },
  { code: 'MZ', name: 'Mozambique', currency: 'MZN', locales: ['pt'] },
  { code: 'AO', name: 'Angola', currency: 'AOA', locales: ['pt'] },
  { code: 'ET', name: 'Ethiopia', currency: 'ETB', locales: ['en'] },
  { code: 'EG', name: 'Egypt', currency: 'EGP', locales: ['ar', 'en'] },
  { code: 'MA', name: 'Morocco', currency: 'MAD', locales: ['ar', 'fr'] },
  { code: 'TN', name: 'Tunisia', currency: 'TND', locales: ['ar', 'fr'] },
  { code: 'DZ', name: 'Algeria', currency: 'DZD', locales: ['ar', 'fr'] },
  { code: 'SN', name: 'Senegal', currency: 'XOF', locales: ['fr'] },
  { code: 'ML', name: 'Mali', currency: 'XOF', locales: ['fr'] },
  { code: 'BF', name: 'Burkina Faso', currency: 'XOF', locales: ['fr'] },
  { code: 'BJ', name: 'Benin', currency: 'XOF', locales: ['fr'] },
  { code: 'TG', name: 'Togo', currency: 'XOF', locales: ['fr'] },
  { code: 'NE', name: 'Niger', currency: 'XOF', locales: ['fr'] },
  { code: 'GN', name: 'Guinea', currency: 'GNF', locales: ['fr'] },
  { code: 'SL', name: 'Sierra Leone', currency: 'SLE', locales: ['en'] },
  { code: 'GM', name: 'Gambia', currency: 'GMD', locales: ['en'] },
  { code: 'CM', name: 'Cameroon', currency: 'XAF', locales: ['fr', 'en'] },
  { code: 'GA', name: 'Gabon', currency: 'XAF', locales: ['fr'] },
  { code: 'CG', name: 'Congo', currency: 'XAF', locales: ['fr'] },
  { code: 'CD', name: 'DR Congo', currency: 'CDF', locales: ['fr'] },
  { code: 'TD', name: 'Chad', currency: 'XAF', locales: ['fr', 'ar'] },
  { code: 'BW', name: 'Botswana', currency: 'BWP', locales: ['en'] },
  { code: 'NA', name: 'Namibia', currency: 'NAD', locales: ['en'] },
  { code: 'MU', name: 'Mauritius', currency: 'MUR', locales: ['en', 'fr'] },
];